name: Rust

on:
  push:
    branches: [mine]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}

      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test

      - name: cargo tarpaulin --out Xml
        run: |
          cargo install cargo-tarpaulin || true
          cargo tarpaulin --out Xml

      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
